import java.math.BigInteger;
import java.util.Random;

public class mainClass {
    static public void main(String[] args){
        BigInteger p, q;

        BigInteger maxLimit = new BigInteger("5000000000000");
        BigInteger minLimit = new BigInteger("25000000000");
        BigInteger bigInteger = maxLimit.subtract(minLimit);

        int len = maxLimit.bitLength();
        Random randNum = new Random();
        p = java.math.BigInteger.probablePrime(len, randNum);

        if (p.compareTo(minLimit) < 0)
            p = p.add(minLimit);
        if (p.compareTo(bigInteger) >= 0)
            p = p.mod(bigInteger).add(minLimit);

        q = java.math.BigInteger.probablePrime(len, randNum);
        if (q.compareTo(minLimit) < 0)
            q = q.add(minLimit);
        if (q.compareTo(bigInteger) >= 0)
            q = q.mod(bigInteger).add(minLimit);

        //generated using parameters
        BBS bbs = new BBS(p,q);

        //randomly generated
        BBS noParameterBBS = new BBS();

        System.out.println("Generator with given p and q (randomly generated in main):\n"+bbs);
        System.out.println("Generator with p and q randomly generated in constructor:\n"+noParameterBBS);

        System.out.println("************************************************");
        System.out.println("Random numbers and bytes generated by the generator with given p and q");
        //generate random numbers

        bbs.generate_numbers(10);
        //generate random bytes
        bbs.generate_bytes(10);
        bbs.testing();
    }
}
